##### Project code:       Net-Zero Toolkit for modelling the financial impacts of low-carbon transition scenarios
##### Date of last edit:  08/04/2019
##### Model author:       Robert Ritz
##### Code author:        Shyamal Patel
##### Dependencies:       Combined model panel generated by the Combine_datasets.R script
##### Notes:              None
##### Called by:          N/A

#--------------------------------------------------------------------------------------------------

##### SECTION 1 - Housekeeping and data read in ----

# Define master_folder and source utils file which contains useful functions
main_save_folder <- "3_Cost_and_competition"
source("utils.R")

# Combined model dataset
model_data <- readRDS("3_Cost_and_competition/Interim/Cleaned_model_panel.rds")

# Source the functions which run the model
source("3_Cost_and_competition/Model.R")

#--------------------------------------------------------------------------------------------------

##### SECTION 2 - Apply Robert Ritz function to the combined model dataset ----

parameter_data <- tibble(discount_rate = 0.0575, #Changing discount rate from 0.0775 to 0.0575
                         competition = 0.5,
                         product_differentiation = "B.0", #Now set at the market-level by default, but can be switched to a single value, similar to the elasticity parameter
                         num_firms = "ON", #Changed from perfect competition (PC = 10^9 firms) to "ON" (endogenous number of firms based on H index)
                         firm_closure = "ON",
                         elasticity = "B.0",
                         stranding = "ON",
                         green_upside = "ON",
                         abatement_opportunities = "ON",
                         cost_pass_through = "ON",
                         sales_impact = "ON",
                         quantity_reallocation = 0.5, # Reset to default values
                         winsorise_scope_1 = "ON", # Winsorisation of scope 1 emissions intensity [overrides quantiles below]
                         winsorise_qlow = 0.05, # Quantile assumptions for Winsorisation
                         winsorise_qhigh = 0.95, # Quantile assumptions for Winsorisation
                         profit_cap = 0.75, # Cap on how much profit subsidiaries can make relative to BAU
                         profit_cap_weight = 0.8) # Weight on cap (80% = 0.8 * profit_cap + 0.2 * original NPV profit)

# Note that variables option only affects company-level results
all_results <- run_model(model_data, parameter_data, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
                                                                           starts_with("profit_post_closure_post_tax"),
                                                                           starts_with("profit_npv_post_closure_post_tax"),
                                                                           starts_with("revenue"))))

subsidiary_results <- all_results[[1]]
market_region_results <- all_results[[2]]
market_results <- all_results[[3]]
region_results <- all_results[[4]]

save_dated(subsidiary_results, "Subsidiary_results", folder = "Output", csv = FALSE)
save_dated(market_region_results, "Market_region_results", folder = "Output", csv = TRUE)
save_dated(market_results, "Market_results", folder = "Output", csv = TRUE)
save_dated(region_results, "Region_results", folder = "Output", csv = TRUE)