##### Project code:       Net-Zero Toolkit for modelling the financial impacts of low-carbon transition scenarios
##### Date of last edit:  25/06/2019
##### Model author:       Robert Ritz
##### Code author:        Shyamal Patel
##### Dependencies:       Combined model panel generated by the Combine_datasets.R script
##### Notes:              None
##### Called by:          N/A

#--------------------------------------------------------------------------------------------------

##### SECTION 1 - Housekeeping and data read in ----

# Define master_folder and source utils file which contains useful functions
main_save_folder <- "3_Cost_and_competition"
source("utils.R")

# Combined model dataset
model_data <- readRDS("3_Cost_and_competition/Interim/Cleaned_model_panel.rds")

# equity, market exposure data for asset impacts JC: can be dropped once using artificial data
equity_data <- readRDS("4_Asset_impacts/Input/Equity_reconciled_2016USD_data.rds")
market_exposure_results <- readRDS("4_Asset_impacts/Input/Revised_product_exposure_results.rds")

# Source the functions which run the model
source("3_Cost_and_competition/Model_test.R")
source("3_Cost_and_competition/Other_model_test.R")
source("3_Cost_and_competition/Power_model_test.R")

#--------------------------------------------------------------------------------------------------

##### SECTION 1a - Generate the data ----

# new dataset - choose one scenario, define artificial data

clean_data <- 
  filter(model_data, scenario == "2DS_Balanced_Transformation") # Paris_NDCs

artificial_data <- clean_data %>%
  mutate(market_cap_2017 = median(market_cap_2017), 
         profit_impact_pct = median(profit_impact_pct),
         revenue_2017 = median(revenue_2017), 
         net_income_2017 = median(net_income_2017), 
         net_income_margin = median(net_income_margin),
         corporation_tax_rate = median(corporation_tax_rate),
         co2_factor = runif(1, min = 0.5, max = 1.5),
         co2_scope_1_2017 = median(co2_scope_1_2017)*co2_factor,
         parent_market == "Artificial") %>%
  sample_n(size = 100)

#--------------------------------------------------------------------------------------------------

##### SECTION 2 - Apply Robert Ritz function to the combined model dataset ----

parameter_data <- tibble(discount_rate = 0.0575, #Changing discount rate from 0.0775 to 0.0575
                         competition = 0.5,
                         product_differentiation = "B.0",  #Now set at the market-level by default, but can be switched to a single value, similar to the elasticity parameter
                         num_firms = "ON", #Changed from perfect competition (PC = 10^9 firms) to "ON" (endogenous number of firms based on H index)
                         firm_closure = "ON",
                         industry_cost_pass_through = 0.7, # this can be changed and will be iterated over in final results.
                         elasticity = "change", #JC: as long as this isn't B.0, it will iterate correctly.
                         stranding = "OFF",
                         green_upside = "OFF",
                         power_model = "OFF",
                         abatement_opportunities = "OFF",
                         cost_pass_through = "ON",
                         sales_impact = "ON",
                         quantity_reallocation = 0.5,  # Reset to default values
                         winsorise_scope_1 = "ON", # Winsorisation of scope 1 emissions intensity [overrides quantiles below]
                         winsorise_qlow = 0.05,  # Quantile assumptions for Winsorisation
                         winsorise_qhigh = 0.95,  # Quantile assumptions for Winsorisation
                         profit_cap = 0.75, # Cap on how much profit subsidiaries can make relative to BAU
                         profit_cap_weight = 0.8) # Weight on cap (80% = 0.8 * profit_cap + 0.2 * original NPV profit)

# Note that variables option only affects company-level results

# define elasticities 
temp = 1:40
elas = temp/10

model_wrap <- function(x) {
  
  temp <- parameter_data %>%
  mutate(elasticity = x) 
  
  # clean_data is quicker than model_data as it drops most scenarios
  other_model(clean_data, temp, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
                                                                starts_with("profit_post_closure_post_tax"),
                                                                starts_with("profit_npv_post_closure_post_tax"),
                                                                starts_with("revenue"))))
}

artificial_wrap <- function(x) {
  
  temp <- parameter_data %>%
    mutate(elasticity = x) # replaces elasticity to mapped value
  print(paste0("elastiticity is", " ", x)) # helps keep track of progress
  
  other_model(artificial_data, temp, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
                                                                      starts_with("profit_post_closure_post_tax"),
                                                                      starts_with("profit_npv_post_closure_post_tax"),
                                                                      starts_with("revenue"))))
}
 

artificial_results <- map(elas, artificial_wrap) %>% # JC: will replace domain 1:3 with elas when ready to run all 40 values
  bind_rows() 

# SECTION 1c - define functions ------------

summarise_artificial <- function(...) {
  
  summarise_vars <- enquos(...)
  
  temp <- artificial_results %>%
    group_by(elasticity, scenario, !!!(summarise_vars)) %>%
    summarise_at(vars(index, index_cap),
                 funs(list(quantile(., probs = c(0.05, 0.1, 0.5, 0.9, 0.95))))) %>%
    mutate_at(vars(index, index_cap),
              funs(map_chr(., paste, collapse = ","))) %>%
    separate(index, into = c("index_p5", "index_p10", "index", "index_p90", "index_p95"), sep = ",") %>%
    separate(index_cap, into = c("index_cap_p5", "index_cap_p10", "index_cap", "index_cap_p90", "index_cap_p95"), sep = ",") %>%
    mutate_at(vars(contains("index")),
              funs(as.numeric(.)))
}

artifical_res2 <- summarise_artificial(elasticity)

# JC: draft elasticity chart - to improve

    plot(artifical_res2$index, type = "b", ylab = "Profit impact under balanced 2DS relative to Paris NDCs")



save_dated(elasticities_results, "elasticities_results", folder = "Output", csv = FALSE)

#--------------------------------------------------------------------------------------------------

##### SECTION 2 - Clean up company-level modelling results -----

# Summarise subsidiary-level results to the company-level
company_results <- elasticities_results %>%
  group_by(elasticity, scenario, company_id, company) %>%
  # Index cap = capped npv profit / market_cap_2017 - 1: rearrange for the below
  mutate(profit_npv_total_cap = market_cap_2017 * (index_cap + 1)) %>%
  summarise_at(vars(starts_with("profit_npv_post_closure_post_tax"), profit_npv_total_cap, starts_with("revenue_"),
                    starts_with("profit_post_closure_pre_tax")),
               funs(sum(., na.rm = TRUE))) %>%
  ungroup()

company_results_for_equity <- company_results %>%
  mutate(profit_npv_total = (rowSums(.[grep("profit_npv_post_closure_post_tax", names(.))]) - profit_npv_post_closure_post_tax_2017)) %>%
  select(elasticity, scenario, company_id, company, profit_npv_total, profit_npv_total_cap)

# Note that the capped value impairment index values cannot be used for fixed income
# company_results_for_fi <- company_results %>%
#   mutate(profit_npv_total = (rowSums(.[grep("profit_npv_post_closure_post_tax", names(.))]) - profit_npv_post_closure_post_tax_2017)) %>%
#   select(scenario, company_id, company, profit_npv_total, profit_npv_total_cap, starts_with("revenue_"),
#          starts_with("profit_post_closure_pre_tax")) %>%
#   rename_at(vars(starts_with("profit_post_closure_pre_tax")),
#             funs(paste0("profit_pre_tax_", stri_extract_all_regex(., "[0-9]+")))) %>%
#   select(-revenue_BAU_quantity_2017)

# Clean up parent market categorisation dataset
market_exposure_results2 <- market_exposure_results %>%
  select(company_id, company, parent_market) %>%
  unique()

#--------------------------------------------------------------------------------------------------

##### SECTION 3 - Calculate equity impacts ----


equity_data2 <- equity_data %>%
  group_by(company_id, company) %>%
  mutate(company_market_cap = sum(market_cap, na.rm = TRUE)) %>%
  ungroup()

# equity_data_for_fi <- equity_data2 %>%
#   select(company_id, company, company_market_cap) %>%
#   unique()

# Compare to company-level market cap to calculate value impairment index
# equity dataset market cap used to ensure results are consistent with the original data [subsidiary-level mcap was present in Subsidiary_results.rds]
equity_results <- equity_data2 %>%
   left_join(market_exposure_results2, by = c("company_id", "company")) %>%
  left_join(company_results_for_equity, by = c("company_id", "company")) %>%
  ungroup() %>%
  mutate(index = profit_npv_total / company_market_cap - 1,
         index_cap = profit_npv_total_cap / company_market_cap - 1)

equity_results2 <- equity_results %>%
  filter(!is.na(scenario))

summarise_equity <- function(...) {
  
  summarise_vars <- enquos(...)
  
  temp <- equity_results2 %>%
    group_by(elasticity, scenario, !!!(summarise_vars)) %>%
    summarise_at(vars(index, index_cap),
                 funs(list(quantile(., probs = c(0.05, 0.1, 0.5, 0.9, 0.95))))) %>%
    mutate_at(vars(index, index_cap),
              funs(map_chr(., paste, collapse = ","))) %>%
    separate(index, into = c("index_p5", "index_p10", "index", "index_p90", "index_p95"), sep = ",") %>%
    separate(index_cap, into = c("index_cap_p5", "index_cap_p10", "index_cap", "index_cap_p90", "index_cap_p95"), sep = ",") %>%
    mutate_at(vars(contains("index")),
              funs(as.numeric(.)))
  
  return(temp)
}

equity_parentmarket_results <- summarise_equity(parent_market)

# JC: draft elasticity chart - to improve
chart <- function(x) {

v <- equity_parentmarket_results %>%
  filter(parent_market == x) 
plot(v$index,type = "o", ylab = "Profit impact under balanced 2DS relative to Paris NDCs")
}

chart("Coal")

