##### Project code:       Net-Zero Toolkit for modelling the financial impacts of low-carbon transition scenarios
##### Date of last edit:  25/06/2019
##### Model author:       Robert Ritz
##### Code author:        Shyamal Patel
##### Dependencies:       Combined model panel generated by the Combine_datasets.R script
##### Notes:              None
##### Called by:          N/A

#--------------------------------------------------------------------------------------------------

##### SECTION 1 - Housekeeping and data read in ----

# Define master_folder and source utils file which contains useful functions
main_save_folder <- "3_Cost_and_competition"
source("utils.R")

# Combined model dataset
model_data <- filter(readRDS("3_Cost_and_competition/Interim/Cleaned_model_panel.rds"), parent_market %in% c("Power generation", "Concrete and cement"))

# new dataset - drop variables, choose one scenario, define data
A <- function(x) median(x)

clean_data <- 
  filter(model_data, scenario == "2DS_Balanced_Transformation", !is.na(profit_impact_pct)) %>%
    mutate(market_cap_2017 = median(market_cap_2017), profit_impact_pct = median(profit_impact_pct),
    revenue_2017 = median(revenue_2017), net_income_2017 = median(net_income_2017), net_income_margin = median(net_income_margin),
    corporation_tax_rate = median(corporation_tax_rate))
  

# Source the functions which run the model
source("3_Cost_and_competition/Model_test.R")

#--------------------------------------------------------------------------------------------------

##### SECTION 2 - Apply Robert Ritz function to the combined model dataset ----

parameter_data <- tibble(discount_rate = 0.0575, #Changing discount rate from 0.0775 to 0.0575
                         competition = 0.5,
                         product_differentiation = 0.1, #Now set at the market-level by default, but can be switched to a single value, similar to the elasticity parameter
                         num_firms = "ON", #Changed from perfect competition (PC = 10^9 firms) to "ON" (endogenous number of firms based on H index)
                         firm_closure = "ON",
                         industry_cost_pass_through = 0.7, # this can be changed and will be iterated over in final results.
                         elasticity = "B.0", #JC: can we remove this line and add it to the iterations?
                         stranding = "ON",
                         green_upside = "ON",
                         abatement_opportunities = "ON",
                         cost_pass_through = "ON",
                         sales_impact = "ON",
                         quantity_reallocation = 0.5, # Reset to default values
                         winsorise_scope_1 = "ON", # Winsorisation of scope 1 emissions intensity [overrides quantiles below]
                         winsorise_qlow = 0.05, # Quantile assumptions for Winsorisation
                         winsorise_qhigh = 0.95, # Quantile assumptions for Winsorisation
                         profit_cap = 0.75, # Cap on how much profit subsidiaries can make relative to BAU
                         profit_cap_weight = 0.8) # Weight on cap (80% = 0.8 * profit_cap + 0.2 * original NPV profit)

parameter_data2 <- tibble(discount_rate = 0.0575, #Changing discount rate from 0.0775 to 0.0575
                         competition = 0.5,
                         product_differentiation = 0.1,  #Now set at the market-level by default, but can be switched to a single value, similar to the elasticity parameter
                         num_firms = "ON", #Changed from perfect competition (PC = 10^9 firms) to "ON" (endogenous number of firms based on H index)
                         firm_closure = "ON",
                         industry_cost_pass_through = 0.7, # this can be changed and will be iterated over in final results.
                         elasticity = "change", #JC: as long as this isn't B.0, it will iterate correctly.
                         stranding = "OFF",
                         green_upside = "OFF",
                         abatement_opportunities = "OFF",
                         cost_pass_through = "ON",
                         sales_impact = "ON",
                         quantity_reallocation = 0.5,  # Reset to default values
                         winsorise_scope_1 = "ON", # Winsorisation of scope 1 emissions intensity [overrides quantiles below]
                         winsorise_qlow = 0.05,  # Quantile assumptions for Winsorisation
                         winsorise_qhigh = 0.95,  # Quantile assumptions for Winsorisation
                         profit_cap = 0.75, # Cap on how much profit subsidiaries can make relative to BAU
                         profit_cap_weight = 0.8) # Weight on cap (80% = 0.8 * profit_cap + 0.2 * original NPV profit)

# Note that variables option only affects company-level results


all_results <- run_model(clean_data, parameter_data, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
                                                                           starts_with("profit_post_closure_post_tax"),
                                                                           starts_with("profit_npv_post_closure_post_tax"),
                                                                           starts_with("revenue"))))


subsidiary_results <- all_results[[1]]
market_region_results <- all_results[[2]]
market_results <- all_results[[3]]
region_results <- all_results[[4]]

save_dated(subsidiary_results, "Subsidiary_results_test", folder = "Output", csv = FALSE)
save_dated(market_region_results, "Market_region_results_test", folder = "Output", csv = TRUE)
save_dated(market_results, "Market_results_test", folder = "Output", csv = TRUE)
save_dated(region_results, "Region_results_test", folder = "Output", csv = TRUE)

# WIP:
# define elasticities 
temp = 1:40
elas = temp/10

model_wrap <- function(x) {

  parameter_data2$elasticity = x

  
  other_model(model_data, parameter_data2, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
                                                                                        starts_with("profit_post_closure_post_tax"),
                                                                                        starts_with("profit_npv_post_closure_post_tax"),
                                                                                        starts_with("revenue"))))
  }

iterate_results <- map(1:3, model_wrap)

subsidiary_results <- iterate_results[[1]]



test_1 <- map(list_values_p_1, wrapper_1 <- function(x) {gbp_function(p_50 = 2, p_20 = 3, p_1 = x)})

# clean-data is much quicker than model_data, as it drops observations outside conc / cement
map_dfr(parameter_data2, other_model(clean_data, parameter_data2, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
                                                                           starts_with("profit_post_closure_post_tax"),
                                                                           starts_with("profit_npv_post_closure_post_tax"),
                                                                           starts_with("revenue")))))

# WIP 2:

# generates power model results
power_results <- power_model(model_data, parameter_data, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
                                                                           starts_with("profit_post_closure_post_tax"),
                                                                           starts_with("profit_npv_post_closure_post_tax"),
                                                                           starts_with("revenue"))))

pwh_carbon_cost_results <- power_results[[1]]


# run other model
other_results <- map(elas, other_model(clean_data, parameter_data2, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
                                                                               starts_with("profit_post_closure_post_tax"),
                                                                               starts_with("profit_npv_post_closure_post_tax"),
                                                                               starts_with("revenue")))))


# map(elas, other_model(clean_data, parameter_data2, "", variables = quo(c("market_cap_2017", starts_with("profit_post_closure_pre_tax"),
#                                                                          starts_with("profit_post_closure_post_tax"),
#                                                                          starts_with("profit_npv_post_closure_post_tax"),
#                                                                          starts_with("revenue")))))


subsidiary_results <- other_results[[1]]
market_region_results <- other_results[[2]]
market_results <- other_results[[3]]
region_results <- other_results[[4]]


save_dated(subsidiary_results, "Subsidiary_results_test2", folder = "Output", csv = FALSE)
save_dated(market_region_results, "Market_region_results_test2", folder = "Output", csv = TRUE)
save_dated(market_results, "Market_results_test2", folder = "Output", csv = TRUE)
save_dated(region_results, "Region_results_test2", folder = "Output", csv = TRUE)