##### Project code:       171211HSB - HSBC Low Carbon Portfolio
##### Date of last edit:  22/01/2019
##### Code author:        Shyamal Patel
##### Description:        This script reads in ICE vehicle scenario and exposure data and models stranding impacts
##### Dependencies:       1.  ICE new capacity data by climate policy scenario
#####                         Older files can be found in the ".../Dated/" folder
#####                         Input files are generated by Data cleaning/0 - Scenarios/Vehicle_deployment.R script

#--------------------------------------------------------------------------------------------------

##### SECTION 1 - Housekeeping, data read in and useful functions for saving/writing files, and QA

packages <- c("tidyverse", "magrittr", "readxl", "here", "stringi", "themeVE", "zoo")
lapply(packages, require, character.only = TRUE)

# Define date for save file names
day <- format(Sys.time(), "%d")
month <- match(format(Sys.time(), "%b"), month.abb)
if(nchar(month) == 1) {month <- paste0("0", month)}
year <- substr(format(Sys.time(), "%Y"), 3, 4)
date <- paste0(year, month, day)

# These functions count the number of missing or zero-value observations in a tibble
na_counter <- function(x) {sum(is.na(x))}
zero_counter <- function(x) {sum(ifelse(x == 0, 1, 0))}

# These functions save base, and dated files in the Interim or Output folder for later use
# Dated files are kept for version control purposes
save_dated <- function(data, name, folder, dated = "YES", csv = "NO") {
  main_path <- paste0("1 - Demand destruction/", folder)
  dated_path <- paste0("1 - Demand destruction/", folder, "/Dated/")
  
  # Save main file
  saveRDS(data, here(main_path, paste0(name, ".rds")))
  # Save dated file (optional)
  if(dated == "YES") {saveRDS(data, here(dated_path, paste0(date, "_", name, ".rds")))}
  # Save dated CSV file (optional)
  if(csv == "YES") {write_csv(data, here(dated_path, paste0(date, "_", name, ".csv")))}
}

# Read in scenario data
ice_scenario_data <- readRDS("1 - Demand destruction/Input/ICE_new_capacity.rds")

# Set discount rate
discount_rate <- 0.0575

#--------------------------------------------------------------------------------------------------

##### SECTION 2 - Clean scenario data

ice_scenario_data %<>%
  select(-`IEA / TIAM Scenario`)

#--------------------------------------------------------------------------------------------------

##### SECTION 3 - Find quantity contraction in automobile (fossil-fired) production for related industries stranding impact

ice_scenario_data %<>%
  gather(key = "year", value = "quantity", -scenario) %>%
  mutate(year = as.numeric(year)) %>%
  filter(year != 2015) %>%
  mutate(NPV_weight = case_when(year == 2020 ~ 0.9,
                                year == 2050 ~ 0.5,
                                TRUE ~ 1),
         NPV_discount_years = year - 2018,
         NPV_quantity = quantity / ((1 + discount_rate) ^ NPV_discount_years)) %>%
  group_by(scenario) %>%
  summarise(NPV_quantity = sum(NPV_quantity)) %>%
  ungroup() %>%
  mutate(BAU_NPV_quantity = mean(ifelse(scenario == "BAU", NPV_quantity, NA_real_), na.rm = TRUE),
         perc_NPV_quantity_impact = (BAU_NPV_quantity - NPV_quantity) / BAU_NPV_quantity)

save_dated(ice_scenario_data, "ICE_vehicles_quantity_contraction", folder = "Output", csv = "YES")