##### Project code:       171211HSB - HSBC Low Carbon Portfolio
##### Date of last edit:  14/01/2019
##### Model author:       Robert Ritz
##### Code author:        Shyamal Patel
##### Dependencies:       Input data files (Input folder)
#####                     1. Model_panel.rds file (created by 0 - Data cleaning/10 - Panel setting/Panel_setting.R script)
#####                     2. DD NPV stranding impacts (created by 2.1 - Fossil demand destruction/Demand destruction R project/EDA_alpha_Price_F_Prod_adj.R script)
#####                     3. Quantity contraction impacts (created by 0 - Data cleaning/9 - Fossil fuel prod/Fossil_fuel_prod_exposure.R script)
#####                     4. Coal_company_NPV_impacts.rds (Coal stranding impacts results file - created by 2.1 - Fossil demand destruction/Coal/Coal modelling.R script)
#####                     5. NPV revenue impacts green upside.rds (Green upside demand creation results file - created by 2.2 - Green upside/Green upside model/Green upside model implementation.R)
##### Called by:          None

##### This script runs the LCP direct carbon cost model based on the model preliminaries generated by the Data cleaning script
##### all model parameterisation dependent variables are calculated below. It is possible to call the function
##### used in the code below from other scripts.
##### The outputs are designed to fit the data requirements for output chart data

####### NB CODE IS FOR SCOPE 1 EMISSIONS ONLY AT THIS STAGE (TRANSLATION OF SCOPE 2 INTO EXISTING CODE NOT YET COMPLETED)
#######    INCONSISTENCY IN BASE YEAR CALIBRATION - carbon prices already non-zero (overwritten to be zero to fit the model better)
####### USE profit impacts valuation model note when reviewing the code as this is more up-to-date than recent notes we have received
####### from Robert Ritz
####### Note that special cases for the utilites sector have now been removed from the code - test this with TN before sign-off
####### NB something strange going on in the corporation tax dataset - how do we deal with this? rates over 100%?!
####### Emissions fudged to be scope 1 + scope 2 to preserve sanity of results
#######  number of firms turned ON 

#--------------------------------------------------------------------------------------------------

##### SECTION 1 - House keeping and data read in

packages <- c("readxl", "tidyverse", "magrittr", "doParallel", "stringi", "themeVE", "ggrepel", "here", "multidplyr")
lapply(packages, require, character.only = TRUE)
rm(packages)

# Define date for save file names
day <- format(Sys.time(), "%d")
month <- match(format(Sys.time(), "%b"), month.abb)
if(nchar(month) == 1) {month <- paste0("0", month)}
year <- substr(format(Sys.time(), "%Y"), 3, 4)
date <- paste0(year, month, day)

# These functions count the number of missing or zero-value observations in a tibble
na_counter <- function(x) {sum(is.na(x))}
zero_counter <- function(x) {sum(ifelse(x == 0, 1, 0), na.rm = TRUE)}

# These functions save base, and dated files in the Interim or Outputs folder for later use
# Dated files are kept for version control purposes
save_dated <- function(data, name = " ", folder, dated = "YES", csv = "NO") {
  main_path <- paste0("3 - Cost and competition/", folder)
  dated_path <- paste0("3 - Cost and competition/", folder, "/Dated/")
  
  if(name == " ") {name <- gsub("_", " ", deparse(substitute(data)))}
  
  # Save main file
  saveRDS(data, here(main_path, paste0(name, ".rds")))
  # Save dated file (optional)
  if(dated == "YES") {saveRDS(data, here(dated_path, paste0(date, "_", name, ".rds")))}
  # Save dated CSV file (optional)
  if(csv == "YES") {write_csv(data, here(dated_path, paste0(date, "_", name, ".csv")))}
}

# Disable timeout
setTimeLimit(cpu = Inf, elapsed = Inf, transient = FALSE)

# Set number of cores for scenario compiling
#c1 <- makeCluster(detectCores() - 1)

# Name formatting function
number_format <- function(x, digits = 1)
{ formatC(x, digits = digits, format = "f") }

# Cleaned financial and emissions dataset read in
panel_model_data <- readRDS("3 - Cost and competition/Input/Model_panel.rds")

##### SET UP AS PART OF 1 - FOSSIL DEMAND DESTRUCTION AND CHANGE FILE PATH
# Oil and gas demand destruction quantity impact results (for sectors related to oil and gas) read in
fossil_fuel_qstrand_results <- readRDS("1 - Demand destruction/Output/Oil_and_gas_quantity_contraction.rds")

# Oil and gas demand destruction analysis results read in
fossil_fuel_dd_results <- readRDS("1 - Demand destruction/Output/DD_NPV_stranding_impacts.rds")

# Coal demand destruction analysis results read in
coal_dd_results <- readRDS("1 - Demand destruction/Output/Coal_company_NPV_impacts.rds")

# Automobiles demand destruction quantity impact results
automobile_qstrand_results <- readRDS("1 - Demand destruction/Output/ICE_vehicles_quantity_contraction.rds") %>%
  select(scenario, perc_NPV_quantity_impact)

# Green upside analysis results read in
green_upside_results <- readRDS("2 - Cleantech markets/Output/NPV_revenue_impacts_green_upside.rds")

# Green upside sector reclassification table read in (temporary - remove when you can)
green_upside_reclassification <- readRDS("3 - Cost and competition/Input/Green_upside_reclassification.rds")

# Set baseline parameters
parameters <- tibble(discount_rate = 0.0575, #Changing discount rate from 0.0775 to 0.0575
                     competition = 0.5,
                     product_differentiation = "B.0", #Now set at the market-level by default, but can be switched to a single value, similar to the elasticity parameter
                     num_firms = "ON", #Changed from perfect competition (PC = 10^9 firms) to "ON" (endogenous number of firms based on H index)
                     firm_closure = "ON",
                     elasticity = "B.0",
                     stranding = "ON",
                     green_upside = "ON",
                     abatement_opportunities = "ON",
                     cost_pass_through = "ON",
                     sales_impact = "ON",
                     quantity_reallocation = 0.5, # Reset to default values
                     quantile_low = 0.05, # Quantile assumptions for Winsorisation
                     quantile_high = 0.95) # Quantile assumptions for Winsorisation

# Define run name
run_name <- str_c(c(number_format(parameters$discount_rate * 100, digits = 2),
                    number_format(parameters$competition),
                    number_format(parameters$product_differentiation),
                    parameters$num_firms, parameters$firm_closure, parameters$elasticity, parameters$stranding, parameters$green_upside,
                    parameters$abatement_opportunities, parameters$cost_pass_through, parameters$sales_impact,
                    number_format(parameters$quantity_reallocation)), collapse = "-")
run_parameters_name <- paste0(run_name, "_parameters")

# Cap on how much profit subsidiaries can make relative to BAU
profit_cap <- 0.75 #(75%)

# Weight on cap (80% = 0.8 * profit_cap + 0.2 * original NPV profit)
profit_cap_weight <- 0.8

#--------------------------------------------------------------------------------------------------

##### SECTION 2 - Define parameter runs based on baseline parameters set

# 2.1 - Direct carbon costs only (abatement options off)
parameters_co2_price_only <- parameters %>%
  mutate(stranding = "OFF",
         abatement_opportunities = "OFF",
         cost_pass_through = "OFF",
         sales_impact = "OFF",
         quantity_reallocation = 0.0)

# 2.2 - Stranding ON (relative to 2.1)
parameters_stranding_on <- parameters_co2_price_only %>%
  mutate(stranding = "ON")

# 2.3 - Abatement ON (relative to 2.2)
parameters_abatement_on <- parameters_stranding_on %>%
  mutate(abatement_opportunities = "ON")

# CPT and sales impact ON (relative to 2.3)
parameters_cpt_sales_on <- parameters_abatement_on %>%
  mutate(cost_pass_through = "ON",
         sales_impact = "ON")

# 2.5 - Quantity reallocation ON (relative to 2.4) - final parameters
parameters_final <- parameters

#--------------------------------------------------------------------------------------------------

##### SECTION 3 - Merge together datasets and adjust model fundamentals for demand destruction, stranding and green upside

oilandgas_qstranding_sectors <- c("O&G T&D", "Oil Equip. & Services", "Petrochemicals")
gas_qstranding_sectors <- c("Gas Distribution", "Gas processing", "Gas retail", "Gas storage")
oil_qstranding_sectors <- c("Oil retail")

# Clean fossil fuel (oil and gas) demand destruction results
fossil_fuel_dd_results %<>%
  rename(ISIN_code = ISIN_Code,
         company = VE_Name,
         scenario = Scenario,
         product = Product) %>%
  ungroup() %>%
  filter(!is.na(ISIN_code)) %>%
  select(scenario, ISIN_code, company, product, ends_with("_pct")) %>%
  unique() %>%
  # Remove B2DS scenario (not used in Low carbon briefing note for 24/08)
  filter(scenario != "B2DS_central") %>%
  gather(key = "impact_type", value = "perc_impact", -(scenario:product)) %>%
  mutate(product_impact_type = paste0(impact_type, "_", product)) %>%
  select(-product, -impact_type) %>%
  spread(key = "product_impact_type", value = "perc_impact") %>%
  arrange(ISIN_code, scenario) %>%
  # Necessary as 2DS_regional scenario does not exist in Rystad dataset
  rename(dd_match = scenario) %>%
  mutate(market = "Exploration and production")

fossil_fuel_qstrand_results %<>%
  rename(qstrand_match = product,
         NPV_Quantity_impact_pct = perc_NPV_quantity_impact)

# Clean coal demand destruction results
coal_dd_results %<>% 
  select(scenario, ISIN_code, company, perc_profit_impact) %>%
  # Remove B2DS scenario (not used in Low carbon briefing note for 24/08)
  filter(scenario != "B2DS_central") %>%
  # Necessary as 2DS_regional scenario does not exist in Rystad dataset
  rename(dd_match = scenario,
         NPV_Profit_impact_pct_Coal = perc_profit_impact) %>%
  mutate(market = "Coal")

# Clean automobile quantity stranding results
automobile_qstrand_results %<>%
  rename(NPV_Quantity_impact_pct = perc_NPV_quantity_impact) %>%
  mutate(qstrand_match = "Automobiles")

# Clean green upside results
green_upside_results %<>%
  ungroup() %>%
  rename(scenario = Scenario,
         company = tr_company,
         ISIN_code = VE_ISIN,
         gr_product = VE_category) %>%
  left_join(green_upside_reclassification) %>%
  rename(market = gr_product_renamed) %>%
  select(scenario, ISIN_code, company, market, Pct_change_NPV_profits) %>%
  mutate(scenario = gsub(" ", "_", scenario)) %>%
  filter(scenario != "B2DS_central") %>%
  mutate(scenario = case_when(scenario == "2DS_delayed" ~ "2DS_delay",
                              scenario == "2DS_high_CCS" ~ "2DS_cheap_ccs",
                              scenario == "2DS_high_efficiency" ~ "2DS_cheap_eff",
                              scenario == "2DS_high_renewables" ~ "2DS_cheap_ren",
                              TRUE ~ scenario)) %>%
  rename(NPV_Profit_impact_pct_Green = Pct_change_NPV_profits,
         dd_match = scenario) %>%
  unique() # Keep only one observation per company-scenario-market combination

# Combine quantity stranding results before join
combined_qstrand_results <- fossil_fuel_qstrand_results %>%
  bind_rows(automobile_qstrand_results) %>%
  rename(dd_match = scenario)

# Merge in 2.1 and 2.2 modelling results (oil and gas, coal, green upside)
panel_model_data %<>%
  # Temp variable for merging in demand destruction impacts dataset
  mutate(dd_match = case_when(scenario == "2DS_regional" ~ "2DS_central",
                              TRUE ~ scenario)) %>%
  # Oil and gas results
  left_join(fossil_fuel_dd_results) %>%
  # Coal results
  left_join(coal_dd_results) %>%
  # Green upside results
  left_join(green_upside_results) %>%
  # Temp variable for merging in quantity stranding impacts
  mutate(qstrand_match = case_when(market %in% oilandgas_qstranding_sectors ~ "All",
                                   market %in% gas_qstranding_sectors ~ "Gas",
                                   market %in% oil_qstranding_sectors ~ "Liquid",
                                   market == "Automobiles" ~ "Automobiles")) %>%
  # Join in quantity stranding variables
  left_join(combined_qstrand_results) %>%
  select(-qstrand_match) %>%
  # Drop DD match variable
  select(-dd_match) %>%
  select(scenario:co2_emissions_scope_3_2017, contains("impact_pct_"), NPV_Quantity_impact_pct, everything()) %>%
  filter(market_cap_2017 > 0) %>%
  mutate(corporation_tax_rate = corporation_tax_rate / 100)

# Remove companies which are outliers for 24/08 report analysis
panel_model_data %<>%
  filter(ISIN_code != "CNE1000003D8") %>% # Remove HUADIAN POWER INTERNATIONAL 'H' from analysis (big outlier and HUADIAN POWER INTL exists separately (same company))
  filter(ISIN_code != "CNE100000HD4") %>% # Remove CHIN.LONGYUAN PWR.GP.'H' from analysis (not a renewable energy equipment company - utility and therefore a big outlier in the renewable market)
  filter(ISIN_code != "KYG3774X1088") %>% # Remove GCL-POLY ENERGY HOLDINGS from analysis (not a renewable energy equipment company - utility and therefore a big outlier in the renewable market)
  filter(ISIN_code != "DE0005190037") # Remove BMW prefeerential shares from analysis (anomalous results)

#--------------------------------------------------------------------------------------------------

##### SECTION 4 - Define the Robert Ritz model function, called by the run model function (PWH first, then other sectors)

run_rr_model <- function(rr_data, rr_carbon_cost_pwh_data = NULL, rr_parameter_data, rr_value_chain_element) {
  
  # Combine carbon cost dataset with RR dataset (defining new variables as carbon_cost_pwh_i) if not NULL
  if(!is.null(rr_carbon_cost_pwh_data))
  {rr_panel_model_run <- rr_data %>% left_join(rr_carbon_cost_pwh_data)
  } else  {rr_panel_model_run <- rr_data
  for(j in model_years) {
    carbon_cost_pwh = rlang::sym(paste0("carbon_cost_pwh_", j))
    rr_panel_model_run %<>%
      mutate(!!carbon_cost_pwh := 0)
  }
  }
  
  # User input on abatement options: if "OFF", replace co2 cost with co2 price in all years, otherwise, change nothing
  for(i in model_years) {
    carbon_price = rlang::sym(paste0("carbon_price_", i))
    carbon_cost = rlang::sym(paste0("carbon_cost_", i))
    carbon_cost_pwh = rlang::sym(paste0("carbon_cost_pwh_", i))
    
    rr_panel_model_run %<>%
      # Adjust carbon costs for abatement opporunities switch (if OFF, carbon costs = carbon price)
      mutate(!!carbon_cost := if(rr_parameter_data$abatement_opportunities == "ON") (!!carbon_cost) else (!!carbon_price),
             !!carbon_cost_pwh := if(rr_parameter_data$abatement_opportunities == "ON") (!!carbon_cost_pwh) else (!!carbon_price))
  }
  
  # User input on product differentiation
  if(rr_parameter_data$product_differentiation != "B.0") {
    rr_panel_model_run %<>%
      mutate(product_differentiation = rr_parameter_data$product_differentiation)
  }
  
  for(i in model_years) {

    t_new <- i
    t_old <- i - 1
    discount_yrs <- i - 2018
    
    # Create variable names for use within loop
    prefix_variables_new <- c("carbon_cost_", "carbon_cost_pwh_", "a_term_", "b_term_", "number_firms_", "c_term_", "industry_cost_pass_through_", "d_relative_co2_intensity_",
                              "rho_cost_pass_through_", "e_sales_impact_", "f_margin_impact_", "profit_pre_closure_pre_tax_", "quantity_pre_closure_",
                              "sector_quantity_pre_closure_", "quantity_reallocated_", "sector_quantity_reallocated_", "quantity_post_closure_",
                              "sector_quantity_post_closure_", "market_share_post_closure_", "profit_post_closure_pre_tax_", 
                              "unit_cost_", "delta_unit_cost_", "price_", "revenue_actual_quantity_", "sector_revenue_actual_quantity_", "profit_margin_",
                              "sector_profit_post_closure_pre_tax_", "sector_profit_margin_", "product_of_share_and_emissions_intensity_scope_1_", "product_of_share_and_emissions_intensity_scope_2_",
                              "product_of_share_and_emissions_intensity_scope_3_", "sector_average_emissions_intensity_scope_1_", "sector_average_emissions_intensity_scope_2_",
                              "sector_average_emissions_intensity_scope_3_", "delta_sector_average_unit_cost_", "sector_average_unit_cost_", "revenue_", "sector_revenue_", "profit_npv_pre_tax_")
    
    prefix_variables_old <- c("quantity_post_closure_", "carbon_cost_", "carbon_cost_pwh_", "sector_profit_margin_", "profit_margin_", "profit_pre_closure_pre_tax_", "price_",
                              "sector_quantity_post_closure_", "profit_post_closure_pre_tax_", "market_share_post_closure_", "unit_cost_", "sector_average_emissions_intensity_scope_1_",
                              "sector_average_emissions_intensity_scope_2_", "delta_sector_average_unit_cost_", "sector_average_unit_cost_")
    
    for (var in prefix_variables_new) {
      assign(paste0(var, "t_new"), rlang::sym(paste0(var, t_new)))
    }
    
    for (var in prefix_variables_old) {
      assign(paste0(var, "t_old"), rlang::sym(paste0(var, t_old)))
    }

    rr_panel_model_run %<>%
      # Remove companies with profit margins over 100%
      mutate(indicator = ifelse(profit_2017 / revenue_2017 > 1, 1, 0)) %>%
      filter(indicator != 1) %>%
      select(-indicator) %>%
      group_by(scenario, market, region) %>%
      mutate(!!delta_unit_cost_t_new := emissions_intensity_scope_1 * ((!!carbon_cost_t_new) - (!!carbon_cost_t_old)) 
                                        + emissions_intensity_scope_2 * ((!!carbon_cost_pwh_t_new) - (!!carbon_cost_pwh_t_old)),
             !!delta_sector_average_unit_cost_t_new := (!!sector_average_emissions_intensity_scope_1_t_old) * ((!!carbon_cost_t_new) - (!!carbon_cost_t_old))
                                                       + (!!sector_average_emissions_intensity_scope_2_t_old) * ((!!carbon_cost_pwh_t_new) - (!!carbon_cost_pwh_t_old)),
             !!unit_cost_t_new := (!!unit_cost_t_old) + (!!delta_unit_cost_t_new),
             !!sector_average_unit_cost_t_new := (!!sector_average_unit_cost_t_old) + (!!delta_sector_average_unit_cost_t_new),
             ## Terms A - D in the profit equation (see annotated verison of Robert Ritz industry note)
             !!a_term_t_new := 1 / (1 + rr_parameter_data$competition - product_differentiation),
             !!b_term_t_new := 1 - product_differentiation,
             !!number_firms_t_new := if(rr_parameter_data$num_firms == "ON") (1 / sum((!!market_share_post_closure_t_old)^2))
                                      else if(rr_parameter_data$num_firms == "OFF") 1
                                      else if(rr_parameter_data$num_firms == "PC") 10^9
                                      else NA,
             !!c_term_t_new := (rr_parameter_data$competition * product_differentiation * (!!number_firms_t_new)) / (1 + rr_parameter_data$competition + product_differentiation * ((!!number_firms_t_new) - 1)),
             !!industry_cost_pass_through_t_new := if(rr_parameter_data$cost_pass_through == "OFF") 0
                                                    else (!!a_term_t_new) * ((!!b_term_t_new) + (!!c_term_t_new)),
             !!d_relative_co2_intensity_t_new := if(rr_parameter_data$num_firms == "OFF") 1
                                                  # Fix to 1 when there is no cost impact (industry average unit cost change is 0)
                                                 else { ifelse(rep(mean(!!delta_sector_average_unit_cost_t_new, na.rm = TRUE) == 0, n()), 1,
                                                         (!!delta_sector_average_unit_cost_t_new) / (!!delta_unit_cost_t_new)) },
             !!rho_cost_pass_through_t_new := if(rr_parameter_data$cost_pass_through == "ON") { (!!a_term_t_new) * ((!!b_term_t_new) + (!!c_term_t_new) * (!!d_relative_co2_intensity_t_new)) }
                                              else {0},
             ## Term E - sales impact
             !!e_sales_impact_t_new := if(rr_parameter_data$sales_impact != "ON") {0}
                                        else if(rr_parameter_data$num_firms != "OFF")
                                              {(- elasticity * (!!industry_cost_pass_through_t_new) * ((!!delta_sector_average_unit_cost_t_new) / (!!sector_average_unit_cost_t_old))
                                                * (1 - (!!sector_profit_margin_t_old)))}
                                        else {(- elasticity * (!!industry_cost_pass_through_t_new) * ((!!delta_unit_cost_t_new) / (!!unit_cost_t_old))
                                                * (1 - (!!profit_margin_t_old)))},
             ## Term F - margin impact
             !!f_margin_impact_t_new := (- (1 - (!!rho_cost_pass_through_t_new)) * ((!!delta_unit_cost_t_new) / (!!unit_cost_t_old))
                                         * (1 - (!!profit_margin_t_old)) / (!!profit_margin_t_old)),
             
             ## Profit - before firm closure, before corporation tax adjustment
             !!profit_pre_closure_pre_tax_t_new := ifelse((!!quantity_post_closure_t_old) == 0, 0,
                                                          (!!profit_post_closure_pre_tax_t_old) * (1 + (!!f_margin_impact_t_new) + (!!e_sales_impact_t_new) + (!!f_margin_impact_t_new) * (!!e_sales_impact_t_new))),
             ## Quantity reallocated due to firm closure (if profit pre-closure and pre-tax is negative)
             !!quantity_pre_closure_t_new := ifelse((!!quantity_post_closure_t_old) == 0, 0,
                                                    (!!quantity_post_closure_t_old) * (1 + (!!e_sales_impact_t_new))),
             !!sector_quantity_pre_closure_t_new := sum((!!quantity_pre_closure_t_new)),
             # TRY REPLACING BELOW WITH IF PROFIT MARGIN < 0 ...
             !!quantity_reallocated_t_new := if(rr_parameter_data$firm_closure == "ON")
                                              {ifelse((!!profit_pre_closure_pre_tax_t_new) < 0, (!!quantity_pre_closure_t_new), 0)}
                                              else {0},
             !!sector_quantity_reallocated_t_new := sum((!!quantity_reallocated_t_new), na.rm = TRUE),
             # Firms receive reallocated quantity units in proportion to their initial shares of the market
             !!quantity_post_closure_t_new := if(rr_parameter_data$firm_closure != "ON")
                                               (!!quantity_pre_closure_t_new)
                                              else ifelse((!!profit_pre_closure_pre_tax_t_new) <= 0, 0,
                                                          (!!quantity_pre_closure_t_new) + rr_parameter_data$quantity_reallocation * (!!sector_quantity_reallocated_t_new) * 
                                                          ((!!quantity_pre_closure_t_new) / ((!!sector_quantity_pre_closure_t_new) - (!!sector_quantity_reallocated_t_new)))),
             !!sector_quantity_post_closure_t_new := sum((!!quantity_post_closure_t_new), na.rm = TRUE),
             !!market_share_post_closure_t_new := ifelse((!!quantity_pre_closure_t_new) == 0, 0,
                                                         (!!quantity_post_closure_t_new) / (!!sector_quantity_post_closure_t_new)),
             
             ## Profit - after firm closure, before corporation tax adjustment
             !!profit_post_closure_pre_tax_t_new := ifelse((!!quantity_pre_closure_t_new) == 0, 0,
                                                           (!!profit_pre_closure_pre_tax_t_new) * ((!!quantity_post_closure_t_new) / (!!quantity_pre_closure_t_new))),
             
             # TRY CHANGING THESE FORMULA - IT ISN'T REALLY 'ACTUAL' COST, SO VERIFY THAT IT IS APPROPRIATE FOR THIS SITUATION - ARE THE QUANTITIES RIGHT?
             !!price_t_new := if(rr_parameter_data$cost_pass_through == "ON")
                                 ((!!price_t_old) + (!!delta_sector_average_unit_cost_t_new) * (1 / (1 + rr_parameter_data$competition - product_differentiation))
                                  * ((1 - product_differentiation) + (rr_parameter_data$competition * product_differentiation * (!!number_firms_t_new)) /
                                  (1 + rr_parameter_data$competition + product_differentiation * ((!!number_firms_t_new) - 1))))
                              else (!!price_t_old),
             !!revenue_t_new := (!!quantity_post_closure_t_new) * (!!price_t_new),
             !!sector_revenue_t_new := sum((!!revenue_t_new), na.rm = TRUE),
             !!profit_margin_t_new := (!!profit_post_closure_pre_tax_t_new) / (!!revenue_t_new),
             !!sector_profit_post_closure_pre_tax_t_new := sum((!!profit_post_closure_pre_tax_t_new), na.rm = TRUE),
             !!sector_profit_margin_t_new := (!!sector_profit_post_closure_pre_tax_t_new) / (!!sector_revenue_t_new),
             
             # Sector average emissions intensity by scope
             !!product_of_share_and_emissions_intensity_scope_1_t_new := (!!market_share_post_closure_t_new) * emissions_intensity_scope_1,
             !!product_of_share_and_emissions_intensity_scope_2_t_new := (!!market_share_post_closure_t_new) * emissions_intensity_scope_2,
             !!product_of_share_and_emissions_intensity_scope_3_t_new := (!!market_share_post_closure_t_new) * emissions_intensity_scope_3,
             !!sector_average_emissions_intensity_scope_1_t_new := sum((!!product_of_share_and_emissions_intensity_scope_1_t_new), na.rm = TRUE),
             !!sector_average_emissions_intensity_scope_2_t_new := sum((!!product_of_share_and_emissions_intensity_scope_2_t_new), na.rm = TRUE),
             !!sector_average_emissions_intensity_scope_3_t_new := sum((!!product_of_share_and_emissions_intensity_scope_3_t_new), na.rm = TRUE),
             
             !!profit_npv_pre_tax_t_new := (!!profit_post_closure_pre_tax_t_new) / ((1 + rr_parameter_data$discount_rate)^(discount_yrs))
      ) %>%
      ungroup()
    
  }
  
  return(rr_panel_model_run)
}

#--------------------------------------------------------------------------------------------------

##### SECTION 5 - Run model function for different scenarios required to produce final results (wrapper around SECTION 4 function)
model_years <- c(2018:2050)

run_model <- function(data, parameter_data, value_chain_element) {
  
  ### SECTION 5a - Preliminary adjustments to the data
  print("Cleaning data")
  # Adjust market cap for asset stranding (if selected by user)
  panel_model_data_blank <- data %>%
    mutate(NPV_Profit_impact_pct_All = if(parameter_data$stranding != "ON") {NA} else{NPV_Profit_impact_pct_All},
           NPV_Profit_impact_pct_Coal = if(parameter_data$stranding != "ON") {NA} else{NPV_Profit_impact_pct_Coal},
           NPV_Quantity_impact_pct = if(parameter_data$stranding != "ON") {NA} else{NPV_Quantity_impact_pct},
           NPV_Profit_impact_pct_Green = if(parameter_data$green_upside != "ON") {NA} else{NPV_Profit_impact_pct_Green},
           market_cap_model = case_when(!is.na(NPV_Profit_impact_pct_All) ~ market_cap_2017 * (1 - NPV_Profit_impact_pct_All),
                                        !is.na(NPV_Profit_impact_pct_Coal) ~ market_cap_2017 * (1 - NPV_Profit_impact_pct_Coal),
                                        !is.na(NPV_Quantity_impact_pct) ~ market_cap_2017 * (1 - NPV_Quantity_impact_pct),
                                        !is.na(NPV_Profit_impact_pct_Green) ~ market_cap_2017 * (1 + NPV_Profit_impact_pct_Green),
                                        TRUE ~ market_cap_2017)) %>%
    select(scenario:market_cap_2017, market_cap_model, everything())
  
  # Create 2017 model variables for use as the first year in the recursive model (2018 - 40)
  panel_model_data_blank %<>%
    ungroup() %>%
    group_by(scenario, region, market) %>%
    # Scale down quantities in proportion to ratio of stranding market cap to pre-stranding market cap (assumed to have no effect on margin or co2 intensity of output)
    mutate(revenue_2017 = revenue_2017 * ifelse(market_cap_2017 == 0, 1, (market_cap_model / market_cap_2017)), #Market_cap == 0 condition relates to company not being active in the region-market
           net_income_2017 = profit_2017 * ifelse(market_cap_2017 == 0, 1, (market_cap_model / market_cap_2017)),
           
           # Save unadjusted CO2 emissions data for charts
           co2_emissions = co2_emissions_scope_1_2017 + co2_emissions_scope_2_2017,
           co2_emissions_scope_1_2017 = co2_emissions_scope_1_2017 * ifelse(market_cap_2017 == 0, 1, (market_cap_model / market_cap_2017)),
           co2_emissions_scope_2_2017 = co2_emissions_scope_2_2017 * ifelse(market_cap_2017 == 0, 1, (market_cap_model / market_cap_2017)),
           co2_emissions_scope_3_2017 = co2_emissions_scope_3_2017 * ifelse(market_cap_2017 == 0, 1, (market_cap_model / market_cap_2017))) %>%
    
    # Adjust up cost and profit to be pre-tax using corporation tax rate
    mutate(total_cost_2017 = ifelse(net_income_2017 >= 0 & revenue_2017 - net_income_2017 / (1 - corporation_tax_rate) >= 0,
                                    revenue_2017 - net_income_2017 / (1 - corporation_tax_rate),
                                    revenue_2017 - net_income_2017),
           profit_pre_closure_pre_tax_2017 = ifelse(revenue_2017 - net_income_2017 / (1 - corporation_tax_rate) >= 0, 1 / (1 - corporation_tax_rate), 1) * 
                                             market_cap_model * (parameter_data$discount_rate / (1 + parameter_data$discount_rate)),
           profit_post_closure_pre_tax_2017 = profit_pre_closure_pre_tax_2017,
           revenue_BAU_quantity_2017 = revenue_2017,
           sector_revenue_actual_quantity_2017 = sum(revenue_BAU_quantity_2017),
           profit_margin_2017 = ifelse(revenue_2017 == 0, 0, profit_pre_closure_pre_tax_2017 / revenue_2017), #Exception written for companies not active in particular markets (at this stage no company should have zero revenue at the global level)
           sector_profit_post_closure_pre_tax_2017 = sum(profit_pre_closure_pre_tax_2017),
           sector_profit_margin_2017 = sector_profit_post_closure_pre_tax_2017 / sector_revenue_actual_quantity_2017) %>%
    
    ### Adjust emissions down based on Winsorisation procedure
    # Store initial emissions as base values
    mutate(co2_emissions_base_scope_1_2017 = co2_emissions_scope_1_2017,
           co2_emissions_base_scope_2_2017 = co2_emissions_scope_2_2017,
           co2_emissions_base_scope_3_2017 = co2_emissions_scope_3_2017) %>%
    mutate(emissions_intensity_scope_1 = co2_emissions_scope_1_2017 / revenue_2017) %>%
    group_by(scenario, market) %>%
    mutate(low_emissions_intensity_scope_1 = quantile(emissions_intensity_scope_1, probs = parameters$quantile_low, na.rm = TRUE),
           high_emissions_intensity_scope_1 = quantile(emissions_intensity_scope_1, probs = parameters$quantile_high, na.rm = TRUE)) %>%
    ungroup() %>%
    mutate(emissions_intensity_scope_1 = case_when(emissions_intensity_scope_1 <= low_emissions_intensity_scope_1 ~ low_emissions_intensity_scope_1,
                                                   emissions_intensity_scope_1 >= high_emissions_intensity_scope_1 ~ high_emissions_intensity_scope_1,
                                                   TRUE ~ emissions_intensity_scope_1)) %>%
    mutate(co2_emissions_scope_1_2017 = revenue_2017 * emissions_intensity_scope_1) %>%
    select(-emissions_intensity_scope_1, -low_emissions_intensity_scope_1, -high_emissions_intensity_scope_1) %>%
    
    # Change units of CO2 emissions from tonnes to Mtonnes (all monetary values are in million US$ (2016))
    # Give zero emissions companies an arbitrary amount of emissions so the model can be run for them (1 tonne)
    mutate(co2_emissions_scope_1_2017 = case_when(co2_emissions_scope_1_2017 == 0 & revenue_2017 >= 0 ~ 1,
                                                  TRUE ~ co2_emissions_scope_1_2017 / 10^6),
           co2_emissions_scope_2_2017 = co2_emissions_scope_2_2017 / 10^6,
           co2_emissions_scope_3_2017 = co2_emissions_scope_3_2017 / 10^6) %>%
    
    mutate(co2_emissions_scope_1_BAU_quantity_2017 = co2_emissions_scope_1_2017,
           co2_emissions_scope_2_BAU_quantity_2017 = co2_emissions_scope_2_2017,
           co2_emissions_scope_3_BAU_quantity_2017 = co2_emissions_scope_3_2017,
           sector_revenue_BAU_quantity_2017 = sum(revenue_BAU_quantity_2017),
           total_cost_BAU_quantity_2017 = total_cost_2017,
           sector_total_cost_BAU_quantity_2017 = sum(total_cost_BAU_quantity_2017),
           total_cost_actual_quantity_2017 = total_cost_BAU_quantity_2017,
           sector_total_cost_actual_quantity_2017 = sum(total_cost_actual_quantity_2017),
           quantity_post_closure_2017 = revenue_BAU_quantity_2017,
           sector_quantity_post_closure_2017 = sum(quantity_post_closure_2017),
           market_share_post_closure_2017 = quantity_post_closure_2017 / sector_quantity_post_closure_2017,
           # WLOG p2017 = 1
           price_2017 = 1,
           quantity_2017 = revenue_2017 / price_2017,
           # Emissions intensity by scope variables
           emissions_intensity_scope_1 = co2_emissions_scope_1_2017 / quantity_2017,
           emissions_intensity_scope_2 = co2_emissions_scope_2_2017 / quantity_2017,
           emissions_intensity_scope_3 = co2_emissions_scope_3_2017 / quantity_2017) %>%
           
    # Rest of data cleaning
    mutate(unit_cost_2017 = total_cost_2017 / quantity_2017,
           sector_average_unit_cost_2017 = sector_total_cost_actual_quantity_2017 / sector_quantity_post_closure_2017,
           # Sectoral average emissions intensity by scope variables
           product_of_share_and_emissions_intensity_scope_1_2017 = emissions_intensity_scope_1 * market_share_post_closure_2017,
           product_of_share_and_emissions_intensity_scope_2_2017 = emissions_intensity_scope_2 * market_share_post_closure_2017,
           product_of_share_and_emissions_intensity_scope_3_2017 = emissions_intensity_scope_3 * market_share_post_closure_2017,
           sector_average_emissions_intensity_scope_1_2017 = sum(product_of_share_and_emissions_intensity_scope_1_2017, na.rm = TRUE),
           sector_average_emissions_intensity_scope_2_2017 = sum(product_of_share_and_emissions_intensity_scope_2_2017, na.rm = TRUE),
           sector_average_emissions_intensity_scope_3_2017 = sum(product_of_share_and_emissions_intensity_scope_3_2017, na.rm = TRUE))
  
  # Set carbon price and cost to be 0 in 2017 (setting up the baseline)
  panel_model_data_blank %<>%
    mutate(carbon_price_2017 = 0,
           carbon_cost_2017 = 0,
           carbon_cost_pwh_2017 = 0)
  
  ### SECTION 5b - Run recursive Robert Ritz model for power sector
  
  panel_model_run <- panel_model_data_blank %>%
    filter(region != "Global")
  
  # Separate out the power sector
  pwh_panel_model_run <- panel_model_run %>%
    filter(market == "Power generation")

  # Run the Robert Ritz model for the power sector
  print("Power sector model")
  pwh_results <- run_rr_model(rr_data = pwh_panel_model_run, rr_parameter_data = parameter_data, rr_value_chain_element = value_chain_element)
  
  ### SECTION 5c - Calculate power sector indirect carbon costs imposed on other sectors
  
  # Find carbon costs from the power sector model run
  pwh_carbon_cost_results <- pwh_results %>%
    select(scenario, region, starts_with("carbon_cost_"), starts_with("industry_cost_pass_through_")) %>%
    unique()
  for (j in model_years) {
    
    carbon_cost_pwh = rlang::sym(paste0("carbon_cost_pwh_", j))
    carbon_cost = rlang::sym(paste0("carbon_cost_", j))
    pwh_cost_pass_through = rlang::sym(paste0("industry_cost_pass_through_", j)) 
    
    pwh_carbon_cost_results %<>%
      mutate(!!carbon_cost_pwh := !!carbon_cost * !!pwh_cost_pass_through)
    
  }
  pwh_carbon_cost_results %<>%
    select(scenario, region, contains("_pwh"))
  
  ### SECTION 5d - Run the Robert Ritz model for all other sectors
  print("All other sectors model")
  all_other_panel_model_run <- panel_model_run %>%
    filter(market != "Power generation")

  all_other_results <- run_rr_model(rr_data = all_other_panel_model_run, rr_carbon_cost_pwh_data = pwh_carbon_cost_results,
                                    rr_parameter_data = parameter_data, rr_value_chain_element = value_chain_element)
  
  ### SECTION 5e - Combine results
  run_results <- pwh_results %>% 
    bind_rows(all_other_results)
  
  ### SECTION 5f - Calculate terminal value of profits, NPV, % impacts and other summary statistics
  
  print("NPV results and aggregation")
  
  # Terminal values and profit summary
  # The first pre-tax terminal profit step is just to generate the Excel values
  panel_model_run_results <- run_results %>%
    mutate(profit_post_closure_pre_tax_terminal = profit_post_closure_pre_tax_2050 * (1 + parameter_data$discount_rate) / parameter_data$discount_rate,
           profit_npv_pre_tax_terminal = profit_npv_pre_tax_2050 / parameter_data$discount_rate,
           profit_npv_pre_tax = rowSums(.[grep("profit_npv_pre_tax_20", names(.))], na.rm = TRUE) + profit_npv_pre_tax_terminal,
           # Apply corporation tax rate if there was corporation tax adjustment to the initial BAU
           profit_npv_post_tax = ifelse(revenue_2017 - net_income_2017 / (1 - corporation_tax_rate) > 0,
                                        profit_npv_pre_tax * (1 - corporation_tax_rate),
                                        profit_npv_pre_tax))
  
  # Generate yearly post-tax profits for charts
  yearly_results <- panel_model_run_results %>%
    mutate_at(vars(starts_with("profit_post_closure_pre_tax_20")), funs(ifelse(revenue_2017 - net_income_2017 / (1 - corporation_tax_rate) > 0,
                                                                               . * (1 - corporation_tax_rate),
                                                                               .))) %>%
    rename_at(vars(starts_with("profit_post_closure_pre_tax_")), funs(paste0("profit_post_tax_",substr(., nchar(.) - 3, nchar(.))))) %>%
    rename(profit_post_tax_terminal_value = profit_post_tax_inal) %>%
    select(scenario, country_of_listing, ISIN_code, company, market, region, starts_with("profit_post_tax_"))
  panel_model_run_results %<>%
    left_join(yearly_results)
  rm("yearly_results")
  
  # Calculate global NPV profit for each company-sector at global and regional levels, drop other variables
  panel_model_run_results %<>%
    select(scenario, country_of_listing, ISIN_code, company, parent_market, region, market, co2_emissions_base_scope_1_2017, co2_emissions_scope_1_2017, market_cap_2017, market_cap_model,
           starts_with("profit_npv_post_tax"), starts_with("profit_post_tax_"), starts_with("price_"), starts_with("quantity_post_closure_"), starts_with("number_firms_"))
  
  # Add back in blank global values dataset
  panel_model_run_global_blank <- panel_model_data_blank %>%
    filter(region == "Global") %>%
    ungroup() %>%
    select(scenario, country_of_listing, ISIN_code, company, region, market, co2_emissions_base_scope_1_2017, co2_emissions_scope_1_2017, market_cap_2017, market_cap_model)
  
  panel_model_run_results %<>%
    bind_rows(y = panel_model_run_global_blank) %>%
    group_by(scenario, ISIN_code) %>%
    mutate(profit_npv_post_tax = ifelse(region == "Global",
                                        sum(profit_npv_post_tax, na.rm = TRUE),
                                        profit_npv_post_tax)) %>%
    mutate_at(vars(starts_with("profit_post_tax_"), starts_with("quantity_post_closure_")), funs(ifelse(region == "Global",
                                                                                                        sum(., na.rm = TRUE),
                                                                                                        .))) %>%
    ungroup()
  
  # Merge together datasets and create index scores
  panel_model_run_results %<>%
    #  full_join(msci_results) %>%
    mutate(index = profit_npv_post_tax / market_cap_2017 - 1) %>%
    #select(-profit_npv_post_tax_guo) %>%
    #select(-intersect(starts_with("profit_post_tax"), ends_with("_guo"))) %>%
    # Capping of results in the power generation market
    select(-starts_with("profit_post_tax_2017")) %>%
    mutate(profit_npv_post_tax_cap = case_when(grepl("GR_", market) ~ profit_npv_post_tax, #Exclude renewables companies from the capping process
                                               profit_npv_post_tax / market_cap_2017 >= (1 + profit_cap) ~ profit_npv_post_tax * (1 - profit_cap_weight) + market_cap_2017 * (1 + profit_cap) * profit_cap_weight,
                                               TRUE ~ profit_npv_post_tax)) %>%
    mutate(index_cap = profit_npv_post_tax_cap / market_cap_2017 - 1)
  
  ##### ISIN codes for concrete and cement
  concrete_and_cement <- c("AU000000JHX1", "CH0012214059", "CNE0000019V8",
                           "CNE1000001W2", "CNE1000002N9", "COD38PA00046",
                           "COT09PA00035", "DE0006047004", "GRS074083007",
                           "ID1000061302", "ID1000106800", "INE047A01021",
                           "INE070A01015", "INE079A01024", "INE481G01011",
                           "JP3449020001", "KYG2113L1068", "MXP225611567",
                           "PK0071501016", "TW0001101004", "TW0001102002")
  
  ##### Edits to NPV results for figures (24/08)
  panel_model_run_results %<>%
    mutate(parent_market = case_when(company == "SHANXI XISHAN C&ELY.PWR. 'A'" ~ "Coking coal",
                                     TRUE ~ parent_market)) %>%
    mutate(parent_market = case_when(ISIN_code %in% concrete_and_cement ~ "Concrete and cement",
                                     TRUE ~ parent_market))
  
  # Summarise company-level results
  company_results <- panel_model_run_results %>%
    group_by(scenario, ISIN_code, company, parent_market) %>%
    summarise(profit_npv_post_tax = sum(profit_npv_post_tax),
              profit_npv_post_tax_cap = sum(profit_npv_post_tax_cap),
              market_cap_2017 = sum(market_cap_2017)) %>%
    ungroup() %>%
    mutate(index = profit_npv_post_tax / market_cap_2017 - 1,
           index_cap = profit_npv_post_tax_cap / market_cap_2017 - 1)
  
  # Market-level results - based on parent markets
  market_results <- panel_model_run_results %>%
    group_by(scenario, parent_market) %>%
    summarise(profit_npv_post_tax = sum(profit_npv_post_tax),
              profit_npv_post_tax_cap = sum(profit_npv_post_tax_cap),
              market_cap_2017 = sum(market_cap_2017)) %>%
    ungroup() %>%
    mutate(index = profit_npv_post_tax / market_cap_2017 - 1,
           index_cap = profit_npv_post_tax_cap / market_cap_2017 - 1) %>%
    mutate(ISIN_code = parent_market,
           company = parent_market) %>%
    select(-parent_market)
  
  # MSCI level results
  msci_results <- panel_model_run_results %>%
    group_by(scenario) %>%
    summarise(profit_npv_post_tax = sum(profit_npv_post_tax),
              profit_npv_post_tax_cap = sum(profit_npv_post_tax_cap),
              market_cap_2017 = sum(market_cap_2017)) %>%
    ungroup() %>%
    mutate(index = profit_npv_post_tax / market_cap_2017 - 1,
           index_cap = profit_npv_post_tax_cap / market_cap_2017 - 1) %>%
    mutate(ISIN_code = "MSCI ACWI",
           company = "MSCI ACWI")
  
  summary_results <- msci_results %>%
    bind_rows(market_results) %>%
    bind_rows(company_results) %>%
    select(scenario, ISIN_code, company, parent_market, everything())
  
  return(list(panel_model_run_results, summary_results, pwh_results, all_other_results))

}

# parameters_co2_only <- parameters %>%
#   mutate(abatement_opportunities = "OFF",
#          cost_pass_through = "OFF")
# 
# parameters_co2_abate <- parameters %>%
#   mutate(cost_pass_through = "OFF")
# 
# parameters_final <- parameters
# 
# ##### Run model itself and compile results
# output_results_list <- run_model(panel_model_data, parameters_co2_only, "")
# panel_model_run_results <- output_results_list[[1]]
# npv_results <- output_results_list[[2]]
# pwh_model_data <- output_results_list[[3]]
# model_data <- output_results_list[[4]]
# 
# save_dated(npv_results, name = "NPV_model_results_carbon_cost", folder = "Output", csv = "YES")  
# 
# output_results_list <- run_model(panel_model_data, parameters_co2_abate, "")
# panel_model_run_results <- output_results_list[[1]]
# npv_results <- output_results_list[[2]]
# pwh_model_data <- output_results_list[[3]]
# model_data <- output_results_list[[4]]
# 
# save_dated(npv_results, name = "NPV_model_results_carbon_cost_abate", folder = "Output", csv = "YES")  

output_results_list <- run_model(panel_model_data, parameters_final, "")
panel_model_run_results <- output_results_list[[1]]
npv_results <- output_results_list[[2]]
pwh_model_data <- output_results_list[[3]]
model_data <- output_results_list[[4]]

save_dated(npv_results, name = "NPV_model_results_final", folder = "Output", csv = "YES")  

# parameter_set <- as.tibble(parameters_co2_only) %>%
#   bind_rows(parameters_co2_abate) %>%
#   bind_rows(parameters_final) %>%
#   mutate(run_name = c("Direct carbon cost", "Abatement", "Cost pass through = Final")) %>%
#   select(run_name, everything())
# 
# save_dated(parameter_set, "Oil_and_gas_results_parameters", folder = "Output", csv = "YES")

