##### Project code:       Net-Zero Toolkit for modelling the financial impacts of low-carbon transition scenarios
##### Date of last edit:  14/02/2019
##### Model author:       Robert Ritz
##### Code author:        Shyamal Patel
##### Dependencies:       Combined model panel generated by the Combine_datasets.R script
##### Notes:              None
##### Called by:          N/A

#--------------------------------------------------------------------------------------------------

##### SECTION 1 - Housekeeping and data read in ----

# Define master_folder and source utils file which contains useful functions
main_save_folder <- "3_Cost_and_competition"
source("utils.R")

# Combined model dataset
model_data <- readRDS("3_Cost_and_competition/Interim/Combined_model_panel.rds")

#--------------------------------------------------------------------------------------------------

##### SECTION 2 - Apply Robert Ritz function to the combined model dataset ----




#--------------------------------------------------------------------------------------------------

##### SECTION 3 - Process model results ----



#--------------------------------------------------------------------------------------------------

##### SECTION 4 - Define parameters and call the file itself ----

# Cap on how much profit company subsidiaries / model division can make relative to BAU
# Weight on cap (80% = 0.8 * profit_cap + 0.2 * original NPV profit)
profit_cap <- 0.75 #(75%)
profit_cap_weight <- 0.8

# Set baseline parameters
parameters <- tibble(discount_rate = 0.0575, #Changing discount rate from 0.0775 to 0.0575
                     competition = 0.5,
                     product_differentiation = "B.0", #Now set at the market-level by default, but can be switched to a single value, similar to the elasticity parameter
                     num_firms = "ON", #Changed from perfect competition (PC = 10^9 firms) to "ON" (endogenous number of firms based on H index)
                     firm_closure = "ON",
                     elasticity = "B.0",
                     stranding = "ON",
                     green_upside = "ON",
                     abatement_opportunities = "ON",
                     cost_pass_through = "ON",
                     sales_impact = "ON",
                     quantity_reallocation = 0.5, # Reset to default values
                     quantile_low = 0.05, # Quantile assumptions for Winsorisation
                     quantile_high = 0.95) # Quantile assumptions for Winsorisation

### Value chain parameter runs
# 2.1 - Direct carbon costs only (abatement options off)
parameters_co2_price_only <- parameters %>%
  mutate(stranding = "OFF",
         abatement_opportunities = "OFF",
         cost_pass_through = "OFF",
         sales_impact = "OFF")

# 2.2 - Stranding ON (relative to 2.1)
parameters_stranding_on <- parameters %>%
  mutate(stranding = "ON",
         abatement_opportunities = "OFF",
         cost_pass_through = "OFF",
         sales_impact = "OFF")

# 2.3 - Abatement ON (relative to 2.2)
parameters_abatement_on <- parameters %>%
  mutate(stranding = "ON",
         abatement_opportunities = "ON",
         cost_pass_through = "OFF",
         sales_impact = "OFF")

# CPT and sales impact ON (relative to 2.3)
parameters_cpt_sales_on <- parameters %>%
  mutate(stranding = "ON",
         abatement_opportunities = "ON",
         cost_pass_through = "ON",
         sales_impact = "ON")






